# Test pod to mount a PV bound to a PVC into a container
# Before starting this pod, apply the PVC with kubectl apply -f pvc.yaml
apiVersion: v1
kind: Pod
metadata:
  name: rohit-choudhary-pvc-tb-access-pod1
spec:
  containers:
    - name: rohit-choudhary-pvc-tb-access-container1

      # we use a small ubuntu base to access the PVC
      image: ubuntu:16.04
      # make sure that we have some time until the container quits by itself
      command: ['sleep', '1h']

      # list of mount paths within the container which will be
      # bound to persistent volumes.
      volumeMounts:
      - mountPath: "/tmp/data/"
        # name of the volume for this path (from the below list)
        name: pvc-mnist
      - mountPath: "/saver/"
        # name of the volume for this path (from the below list)
        name: pvc-tensorboard

  volumes:
    # User-defined name of the persistent volume within this configuration.
    # This can be different from the name of the PVC.
    - name: pvc-mnist
      persistentVolumeClaim:
        # name of the PVC this volume binds to
        claimName: rohit-choudhary-lfvs-data
    - name: pvc-tensorboard
      persistentVolumeClaim:
        # name of the PVC this volume binds to
        claimName: rohit-choudhary-lfvs-tensordata


