apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  # the name of the PVC, we refer to this in the container configuration
  # again, preprend your username to make the name unique
  # note that this has the same name as the claim before, so it will
  # reuse the data if it already exists.
  name: rohit-choudhary-lfvs-data

spec:
  resources:
    requests:
      # storage resource request. This PVC can only be bound to volumes which
      # have at least 8 GiB of storage available.
      storage: 5Gi

  # the requested storage class, see tutorial.
  storageClassName: local-ssd

  # leave these unchanged, they must match the PV type, otherwise binding will fail
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  # the name of the PVC, we refer to this in the container configuration
  # again, preprend your username to make the name unique
  name: rohit-choudhary-lfvs-tensordata

spec:
  resources:
    requests:
      # storage resource request. This PVC can only be bound to volumes which
      # have at least 8 GiB of storage available.
      storage: 5Gi

  # the requested storage class, see tutorial.
  storageClassName: local-tensorboard
  
  # leave these unchanged, they must match the PV type, otherwise binding will fail
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem

